# TVRA Toolkit
Threat, Vulnerability and Risk Assessment for MedSecurance / IoMT

This repository contains a modular toolkit for **Threat, Vulnerability and Risk Assessment (TVRA)**, designed to support **Internet of Medical Things (IoMT)** and other safety-critical systems within the **MedSecurance** Project.

It brings together:
- Vulnerability scanning
- Context-aware risk assessment (TVRA + Spyderisk)
- AI-assisted threat modelling and mitigation
- Centralised evidence management
- Integration hooks for Assurance / O-ETB and other MedSecurance components

---

## Key Features

### Vulnerability Scanning

Identify exposed services and weaknesses in IOMT deployment.

- Lightweight service-level scanning using **OpenVAS** feeds (via the TVRA toolkit)  
- Detection of:
  - Known CVEs (firmware / OS)
  - Misconfigurations (weak crypto, default credentials)
  - Insecure or deprecated services  
- Outputs formatted for downstream risk reasoning and evidence storage

---
### Contextual Risk Assessment

Perform structured, ISO/IEC 27005–inspired risk assessments tailored for IoMT and cyber-physical systems.

- System- and component-level risk modelling  
- Context establishment (assets, architecture, environment, regulations)  
- Threat modelling aligned with frameworks such as **STRIDE** and **MITRE ATT\&CK**  
- Exportable risk registers, attack paths, and recommendation artefacts

---
### Evidence Management (`centralDB`)

Store all risk and vulnerability artefacts in a **central evidence repository**.

- Versioned storage of evidence files (reports, JSON, logs, diagrams)  
- Metadata management with **TinyDB** (timestamps, comments, hashes)  
- REST API for:
  - Uploading files or JSON artefacts  
  - Listing and retrieving evidence by category/filename/version  
  - Verifying integrity (SHA-256)  
  - Deleting individual versions or full file histories  

This service acts as the **single point of truth** for evidence generated by TVRA, IoMT communication tools, and Assurance / O-ETB.

---

### Assurance / O-ETB Integration (`Assurance/build`)

Integrate with the **O-ETB (Open Evidential Tool Bus)** to support evidence-driven assurance cases.

- Docker build for the Assurance / O-ETB environment  
- Combined Prolog + Python + FastAPI container  
- Designed to retrieve required evidence from `centralDB` on demand  
- Plays the evidence-consuming role in the broader MedSecurance pipeline

---

## Repository Structure

```text
.
├── Assurance/
│   └── build/          # Docker build for O-ETB / Assurance integration
│       ├── Dockerfile
│       ├── BUILD_GUIDE.md
│       ├── entrypoint.sh
│       └── README.md
│
├── Final_Files/        # Threat modelling & mitigation final files
│   ├── CONFIGURATION.md
│   ├── Mitigation_client.py
│   ├── Mitigation_endpoint_remote.py
│   ├── config.py
│   ├── prompts.py
│   ├── remote_ai_client.py
│   ├── requirements.txt
│   ├── start_services.sh
│   ├── threat_model.json
│   ├── threat_model_client.py
│   ├── threat_model_endpoint.py
│   └── get_threats_OUTPUT.json (example output)
│
├── centralDB/          # Evidence Management System (API + storage)
│   ├── app/
│   ├── sample/
│   ├── Dockerfile
│   ├── requirements.txt
│   ├── example_agent.py
│   └── README.md
│
├── deployment/         # TVRA deployment stack
│   ├── src/
│   ├── spyderisk/
│   ├── Dockerfile
│   ├── docker-compose.yml
│   ├── docker-compose-dev.yml
│   ├── deploy_tvra.sh
│   ├── stop_tvra.sh
│   ├── .env
│   └── sources.list
│
└── docs/               # Documentation & example artefacts
    ├── IoMT_Model_INPUT.json
    ├── diagrams.md
    ├── openapi.json
    ├── user_guide.md
    ├── get_threats_OUTPUT.json
    ├── get_threats_raw_mode_OUTPUT.json
    ├── get_recommednation_full_OUTPUT.json
    ├── vuln_scanner_get_report_OUTPUT.html
    └── vuln_scanner_get_report_OUTPUT.json
```
---
## Installation

> **Note:** For realistic deployments, this toolkit is intended to run on a Linux host with Docker, especially when placed close to the networks and devices being assessed.

### Prerequisites

- [Docker](https://www.docker.com/)
- [Docker Compose](https://docs.docker.com/compose/)
- **Python 3.10+** if you plan to run components like `Final_Files` or `centralDB` directly outside of Docker.

---

### 1. Clone the Repository

```bash
git clone https://github.com/MedSecurance/TVRA.git
cd TVRA
```

### 2. Configure Environment Variables (TVRA Stack)
Most deployment settings are controlled via the `.env` file in `deployment/`.

```bash
cd deployment
nano .env
```
Important variables typically include:
  - Database credentials and connection strings
  - Service hostnames and ports

External URLs for:
  - Threat modelling services
  - Evidence Manager (`centralDB`)
  - Assurance / O-ETB or other MedSecurance components

Check inline comments in .env and docs/user_guide.md for the full set of variables and their roles.

### 3. Build and Start the TVRA Stack
From the `deployment/` directory:

```bash
# Option A: helper script
./deploy_tvra.sh

# Option B: docker compose directly
docker compose -f docker-compose.yml up --build
```
This will:
  - Build images for the TVRA services (risk modeller, APIs, supporting tools)
  - Start the containers as defined in docker-compose.yml

To stop the stack:

```bash
./stop_tvra.sh
# or
docker compose down
```

## 4. Run the Evidence Manager (`centralDB`)
You can run `centralDB` as part of your compose setup or independently.

From `centralDB/`:

```bash
cd centralDB
docker build -t evidence-manager .
docker run -p 9000:9000 -v ./local_data:/app/data evidence-manager
```

Access the API documentation at:
  - http://localhost:9000/docs

From there you can:
  - Upload risk and vulnerability reports, JSON threat outputs, etc.
  - List, download, and delete evidence per category/filename/version.

### 5. Build and Run the Assurance / O-ETB Container
From `Assurance/build/`:

```bash
cd Assurance/build

# Build image (see BUILD_GUIDE.md for any repo layout assumptions)
docker build -t o-etb:latest .

docker run -it --rm \
  -p 8080:8080 \
  -v "$(pwd)/Assurance:/Assurance" \
  o-etb:latest
```
Access the O-ETB FastAPI interface:
  - http://localhost:8080/docs

### 6. Threat Modelling Services (`Final_Files`)
From `Final_Files/`:

```bash
cd Final_Files

python -m venv .venv
source .venv/bin/activate   # On Windows: .venv\Scripts\activate

pip install -r requirements.txt

./start_services.sh
```

Use:
  - threat_model_client.py to submit models and retrieve threats
  - Mitigation_client.py to obtain mitigation suggestions

Configuration and example usage are documented in CONFIGURATION.md.

### Accessing Services
Exact URLs/ports depend on your .env and docker-compose.yml, but common defaults are:
  - TVRA / Risk APIs – see deployment/docker-compose.yml and docs/openapi.json
  - Evidence Manager (centralDB) – http://localhost:9000/docs
  - Assurance / O-ETB – http://localhost:8080/docs
  - Threat Modelling Endpoints – as specified in Final_Files/CONFIGURATION.md

Deploying Individual Components
You don’t have to run the full stack. You can deploy components independently:
  - TVRA core only: Keep only core services in deployment/docker-compose.yml (risk engine, DB, API).
  - centralDB only: Build and run from centralDB/ as shown above to act as a standalone evidence store.
  - Assurance / O-ETB only: Deploy from Assurance/build/ and connect it to an existing evidence manager.
  - Threat modelling only: Run the endpoints and clients in Final_Files/ on a separate host if needed.


### License
This project is licensed under the MIT License.
